### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by nomyTx** [comment]
The GUI installer is only for Windows.

**Comment by ghost** [comment]
> The GUI installer is only for Windows.

The "Download Installer" button on the website leads to the gui installer and the link here was broken so i thought it should be replaced with the same.

**Comment by ghost** [comment]
can always change it to the cli installer if need be

**Comment by mdrakea** [comment]
but.. the only thing your PR does is change it to the GUI installer? so your PR is pointless?

**Comment by ghost** [comment]
im sorry i dont follow... it is supposed to change a broken link and it does?

**Comment by kckarnige** [comment]
> but.. the only thing your PR does is change it to the GUI installer? so your PR is pointless?

The link in the docs right now is broken, this pr intends to update it to the GUI installer

**Pull request closed without merging**
