### PR TITLE
Pwease add my package 🥺👉👈

### PR DESCRIPTION
**Pull request by kckarnige**
Please add my useless package that no one cares about and has no practical use 🥺👉👈💞

### CODE REVIEW

**Comment by nomyTx** [comment]
It's called a package.

**Comment by kckarnige** [comment]
_Ik that_

**Comment by kckarnige** [comment]
Oh damn I said that in the desc, whoops

**Comment by kckarnige** [comment]
Fixed 👌

**Comment by kckarnige** [comment]
Why wasn't this closed a while ago lmao

**Pull request closed without merging**
